language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - grunt test
  - phpunit -d memory_limit=1024M

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true